server:
  port: 8090

spring:
  profiles:
    include:
      - preson
  jpa:
    hibernate:
      ddl-auto: none
  #spring.jpa.hibernate.ddl-auto参数有以下配置:none, update, create, create-drop,含义如下:
  #none 这个是默认参数，不改版数据库结构。
  #update Hibernate会改变数据库的结构根据我们的java实体。
  #create 可创建数据库，但不会删除它。
  #create-drop 创建数据库，每次断开连接时自动删除。
  #https://blog.csdn.net/zzq900503/article/details/81070441
  datasource:
    url: jdbc:mysql://192.168.117.128:3306/my_spring_boot
    username: 'springuser'   #it should be username not name
    password: 'Password1'

